# Generated by Django 2.1.3 on 2018-11-23 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etat_ope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etat_ope', models.BooleanField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pompe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=2, unique=True)),
                ('gpio_ONOFF', models.IntegerField(default=0)),
                ('gpio_AM', models.IntegerField(default=0)),
                ('gpio_AC', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OFF', 'Arrêt'), ('ON', 'Marche'), ('KO_NACK', 'Défaut non acquitté'), ('KO_ACK', 'Défaut acquitté'), ('AL_NACK', 'Alarme non acquittée'), ('AL_ACK', 'Alarme acquittée')], default='ON', max_length=7)),
                ('date_etat', models.DateTimeField(auto_now_add=True, verbose_name='date')),
                ('date_ack', models.DateTimeField(verbose_name='date')),
                ('pompe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CREDapp.Pompe')),
            ],
        ),
        migrations.AddField(
            model_name='etat_ope',
            name='pompe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CREDapp.Pompe'),
        ),
    ]
